services:
  catalogdb:
    image: postgres:15
    
  basketdb:
    image: postgres:15
    
  distributedcache:
    image: redis:6.2-alpine
    
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  messagebroker:
    image: rabbitmq:management
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateways:
    image: ${DOCKER_REGISTRY-}yarpapigateways
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateways/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:





