services:
  catalogdb:
    image: postgres:15
    
  basketdb:
    image: postgres:15
    
  distributedcache:
    image: redis:6.2-alpine
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

